import jsPDF from "jspdf";
import type { AnalysisResult } from "@/types/agent";
import { PAGE, PDF_THEME, setSectionTitle } from "./pdfTheme";
import { drawCard, addWrappedText, drawBadge, recommendationColor } from "./pdfHelpers";

export function drawConclusion(doc: jsPDF, result: AnalysisResult) {
    let y = PAGE.marginY;
    
    setSectionTitle(doc, "INVESTMENT CONCLUSION", y);
    y += 15;

    // Final Verdict Hero
    drawCard(doc, PAGE.marginX, y, PAGE.width - PAGE.marginX * 2, 45);
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.textLight);
    doc.text("FINAL VERDICT", PAGE.marginX + 6, y + 8);
    
    drawBadge(doc, result.verdict.toUpperCase(), PAGE.marginX + 6, y + 14, recommendationColor(result.verdict));
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.text);
    
    y = addWrappedText(doc, result.executiveSummary.action, y + 26, 10, PAGE.width - PAGE.marginX * 2 - 12, PAGE.marginX + 6, PDF_THEME.text) + 20;

    // Investment Profile
    const cardWidth = (PAGE.width - PAGE.marginX * 2 - 10) / 2;
    
    drawCard(doc, PAGE.marginX, y, cardWidth, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...PDF_THEME.textLight);
    doc.text("TARGET INVESTOR PROFILE", PAGE.marginX + 6, y + 8);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.text);
    addWrappedText(doc, result.executiveSummary.investorType, y + 16, 9, cardWidth - 12, PAGE.marginX + 6, PDF_THEME.text);
    
    drawCard(doc, PAGE.marginX + cardWidth + 10, y, cardWidth, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...PDF_THEME.textLight);
    doc.text("INVESTMENT HORIZON", PAGE.marginX + cardWidth + 16, y + 8);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.text);
    addWrappedText(doc, result.executiveSummary.investmentHorizon, y + 16, 9, cardWidth - 12, PAGE.marginX + cardWidth + 16, PDF_THEME.text);

    y += 40;

    // Outlook
    drawCard(doc, PAGE.marginX, y, PAGE.width - PAGE.marginX * 2, 45);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.textLight);
    doc.text("FORWARD-LOOKING OUTLOOK", PAGE.marginX + 6, y + 8);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...PDF_THEME.text);
    addWrappedText(doc, result.executiveSummary.outlook, y + 16, 10, PAGE.width - PAGE.marginX * 2 - 12, PAGE.marginX + 6, PDF_THEME.text);

    y += 55;
    
    // Disclaimer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(...PDF_THEME.textLight);
    
    const disclaimer = "DISCLAIMER: This report is for informational purposes only and does not constitute financial advice. The analysis is generated by an artificial intelligence system and may contain errors. Investing involves risk, including the possible loss of principal. Past performance does not guarantee future results. Investors should conduct their own due diligence or consult with a qualified financial advisor before making any investment decisions.";
    
    addWrappedText(doc, disclaimer, y, 9, PAGE.width - PAGE.marginX * 2, PAGE.marginX, PDF_THEME.textLight);
    
    // Do not addPage() here so watermark and footer can be drawn on this final page if needed, 
    // although generateReport will handle applying watermarks to all pages anyway.
}
