import jsPDF from "jspdf";

type Color = readonly [number, number, number];

export const PDF_THEME: {
    primary: Color;
    secondary: Color;
    accent: Color;
    success: Color;
    warning: Color;
    danger: Color;
    text: Color;
    muted: Color;
    border: Color;
    background: Color;
} = {
    primary: [16, 185, 129],
    secondary: [39, 39, 42],
    accent: [59, 130, 246],

    success: [22, 163, 74],
    warning: [234, 179, 8],
    danger: [220, 38, 38],

    text: [24, 24, 27],
    muted: [113, 113, 122],

    border: [228, 228, 231],
    background: [250, 250, 250],
};

export const PAGE = {
    width: 210,
    height: 297,

    marginX: 16,
    marginY: 18,

    contentWidth: 178,
};

export function setTitle(doc: jsPDF, title: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(...PDF_THEME.secondary);

    doc.text(title, PAGE.marginX, 24);
}

export function setSectionTitle(
    doc: jsPDF,
    title: string,
    y: number
) {
    doc.setDrawColor(...PDF_THEME.primary);
    doc.setLineWidth(0.6);

    doc.line(
        PAGE.marginX,
        y,
        PAGE.width - PAGE.marginX,
        y
    );

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(...PDF_THEME.secondary);

    doc.text(title, PAGE.marginX, y + 8);
}

export function drawFooter(doc: jsPDF) {
    const pageCount = doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        doc.setFontSize(9);
        doc.setTextColor(...PDF_THEME.muted);

        doc.text(
            "Generated by AI Investment Research Agent",
            PAGE.marginX,
            PAGE.height - 8
        );

        doc.text(
            `Page ${i}`,
            PAGE.width - PAGE.marginX,
            PAGE.height - 8,
            {
                align: "right",
            }
        );
    }
}

export function drawWatermark(doc: jsPDF) {
    const pageCount = doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);

        doc.setFontSize(35);

        doc.setTextColor(240, 240, 240);

        doc.text(
            "AI INVESTMENT REPORT",
            PAGE.width / 1.5,
            PAGE.height/1.5,
            {
                angle: 45,
                align: "center",
            }
        );
    }
}   